-- [P1-PLAN-LOTE-209 · 2026-09-24] `master_ingredients.shelf_life_days` deja de ser relleno.
--
-- 326 de 349 filas valían 14 días: aceite de oliva, sal, canela y habichuelas secas igual que el aguacate o la leche.
-- Lo sabían tres pases que lo esquivaban en código (P1-PLAN-LOTE-201 en las anotaciones de la Nevera que lee la IA,
-- P1-PLAN-LOTE-202 en el delta de la lista, P1-PDF-2 en perecedero/estable), pero el DATO seguía diciendo 14 para
-- cualquier otra pantalla o consulta que lo lea. Permiso del dueño (24-sep): «tienes permiso para corregir mi base».
--
-- LA REGLA: el plazo en FRESCO del SSOT de durabilidad (`pantry_durability.classify(nombre, categoría)`), el mismo que
-- ya gobierna el registry, el blueprint de compra única y el validador de fidelidad:
--   pantry  (seco, enlatado, aceites, especias) ....... 180 / 365
--   cold    (raíces, cítricos, repollo, huevo, quesos) . 10-60
--   fresh   (hojas, frutas blandas, aguacate, leche) .. 5-7
-- NO se tocan:
--   · `freezable` (carnes, pescado, mariscos: 3 días en fresco, 90 congelados) ni `frozen` (congelado de fábrica): su
--     plazo depende del CONGELADOR del usuario, que el catálogo no conoce — un 3 fijo pondría «caducado» al pollo que el
--     usuario congeló, y un 90 le diría que el pollo fresco aguanta tres meses;
--   · `cold` cuyo SSOT también dice 14 (yogur, quesos frescos, embutidos de nevera): ya es su valor;
--   · las 23 filas que NO valen 14: alguien las curó a mano (pan 3, espinaca 5, atún 730) y ganan.
-- Generado leyendo la base (solo lectura) con `pantry_durability.classify` del código desplegado: 256 filas cambian,
-- 70 siguen en 14 (37 freezable + 4 frozen + 29 cold/14).
--
-- Idempotente: filtra por `name` Y por el relleno (`shelf_life_days = 14`) — re-aplicarla no toca nada, y una fila que
-- alguien cure después no se pisa.

UPDATE public.master_ingredients AS m
SET shelf_life_days = v.dias
FROM (VALUES
    ('Aceite de achiote', 180),
    ('Aceite de coco', 180),
    ('Aceite de oliva', 180),
    ('Aceite de sésamo', 180),
    ('Aceite vegetal', 180),
    ('Aceitunas', 365),
    ('Aceitunas rellenas', 365),
    ('Acelgas', 7),
    ('Achiote', 180),
    ('Aderezo ranch', 180),
    ('Adobo', 180),
    ('Aguacate', 7),
    ('Ajo', 60),
    ('Ajo en polvo', 180),
    ('Ajonjolí', 180),
    ('Ají cubanela', 10),
    ('Ají morrón', 10),
    ('Albahaca seca', 180),
    ('Alcachofa', 10),
    ('Alcaparrado', 365),
    ('Alioli', 180),
    ('Almendra marcona', 180),
    ('Almendras fileteadas', 180),
    ('Anchoas', 180),
    ('Apio', 10),
    ('Arenque', 180),
    ('Arequipe', 180),
    ('Arracacha', 21),
    ('Arroz blanco', 180),
    ('Arroz integral', 180),
    ('Arándanos', 10),
    ('Arándanos rojos', 10),
    ('Auyama', 45),
    ('Avena', 180),
    ('Azafrán', 180),
    ('Azúcar morena', 180),
    ('Bacalaítos', 5),
    ('Bagels', 7),
    ('Batata', 30),
    ('Berenjena', 10),
    ('Berro', 7),
    ('Bok choy', 10),
    ('Borojó', 21),
    ('Brócoli', 10),
    ('Bulgur', 180),
    ('Butifarra', 30),
    ('Cacao en polvo', 180),
    ('Calabacín', 10),
    ('Canela en polvo', 180),
    ('Casabe', 180),
    ('Casabe albahaca', 180),
    ('Cebada', 180),
    ('Cebolla', 60),
    ('Cebolla en polvo', 180),
    ('Cebollín', 7),
    ('Cecina', 30),
    ('Cereza maraschino', 7),
    ('Champiñones', 7),
    ('Champús', 180),
    ('Chile ancho', 180),
    ('Chile chipotle', 180),
    ('Chile de árbol', 180),
    ('Chile en polvo', 180),
    ('Chile guajillo', 180),
    ('Chile habanero', 10),
    ('Chile jalapeño', 10),
    ('Chile mulato', 180),
    ('Chile pasilla', 180),
    ('Chile poblano', 10),
    ('Chile serrano', 10),
    ('Chili con carne', 365),
    ('Chinola', 21),
    ('Chistorra', 30),
    ('Chocolate de mesa', 180),
    ('Chontaduro', 21),
    ('Chorizo español', 30),
    ('Cilantro', 7),
    ('Ciruela', 7),
    ('Ciruela pasa', 180),
    ('Coco', 30),
    ('Coditos', 180),
    ('Coles de Bruselas', 10),
    ('Coliflor', 10),
    ('Comino', 180),
    ('Cundeamor', 7),
    ('Curry en polvo', 180),
    ('Curuba', 7),
    ('Cúrcuma', 180),
    ('Durazno en almíbar', 365),
    ('Duraznos', 7),
    ('Dátiles', 180),
    ('Ensalada de macarrones', 5),
    ('Epazote', 7),
    ('Espaguetis', 180),
    ('Especias para arroz con dulce', 180),
    ('Espárragos', 7),
    ('Feijoa', 7),
    ('Fideos', 180),
    ('Flor de Jamaica', 180),
    ('Fresas', 7),
    ('Frijol cargamanto', 180),
    ('Frijoles horneados', 365),
    ('Frijoles pintos', 180),
    ('Frijoles refritos', 365),
    ('Galletas Graham', 180),
    ('Gandules', 180),
    ('Garbanzos', 180),
    ('Granada', 30),
    ('Granadilla', 7),
    ('Guanábana', 7),
    ('Guascas', 180),
    ('Guayaba', 7),
    ('Guineo', 7),
    ('Guineo verde', 7),
    ('Guisantes secos', 180),
    ('Habas', 180),
    ('Habichuelas blancas', 180),
    ('Habichuelas negras', 180),
    ('Habichuelas rojas', 180),
    ('Harina de Negrito', 180),
    ('Harina de maíz precocida', 180),
    ('Harina de yuca', 180),
    ('Higo', 7),
    ('Hoja santa', 7),
    ('Huevos rellenos', 5),
    ('Huitlacoche', 7),
    ('Hummus', 5),
    ('Jamón ibérico', 30),
    ('Jamón serrano', 30),
    ('Jarabe de arce', 180),
    ('Judías blancas', 180),
    ('Judías pintas', 180),
    ('Jícama', 21),
    ('Kale', 7),
    ('Kiwi', 21),
    ('Kétchup', 180),
    ('Laurel', 180),
    ('Leche', 7),
    ('Leche de almendras', 365),
    ('Leche de avena', 365),
    ('Leche de cabra en polvo', 365),
    ('Leche de coco', 365),
    ('Leche de soya', 365),
    ('Lechosa', 7),
    ('Lechuga', 7),
    ('Lechuga romana', 7),
    ('Lentejas', 180),
    ('Limón', 30),
    ('Lomo embuchado', 30),
    ('Lulo', 7),
    ('Malvaviscos', 180),
    ('Mandarina', 21),
    ('Mango', 7),
    ('Mantequilla de almendras', 180),
    ('Mapuey', 21),
    ('Masa para pie', 180),
    ('Mazapán', 180),
    ('Maíz dulce en granos', 365),
    ('Melón', 10),
    ('Membrillo', 30),
    ('Membrillo dulce', 180),
    ('Merey', 180),
    ('Mezcla para panqueques', 180),
    ('Miel', 180),
    ('Mora', 7),
    ('Mostaza', 180),
    ('Nabo', 21),
    ('Naranja', 30),
    ('Nopal', 10),
    ('Nori', 180),
    ('Nueces mixtas', 180),
    ('Nueces pecanas', 180),
    ('Nuez de Castilla', 180),
    ('Níspero', 7),
    ('Orégano dominicano', 180),
    ('Palmito', 365),
    ('Pan blanco familiar', 7),
    ('Pan de maíz', 5),
    ('Pan integral familiar', 7),
    ('Pan integral personal', 7),
    ('Pan rallado', 180),
    ('Panapén', 21),
    ('Panceta ibérica', 30),
    ('Panecillos de mantequilla', 5),
    ('Panecillos ingleses', 7),
    ('Panela', 180),
    ('Papa', 45),
    ('Pasas', 180),
    ('Pasta integral', 180),
    ('Pepperoni', 30),
    ('Pera', 21),
    ('Perejil', 7),
    ('Pimentón', 180),
    ('Pimienta negra', 180),
    ('Pique', 180),
    ('Pistachos', 180),
    ('Piña', 7),
    ('Piñones', 180),
    ('Plátano maduro', 7),
    ('Plátano verde', 10),
    ('Pretzels', 180),
    ('Puerro', 10),
    ('Queso cheddar', 45),
    ('Queso de papa', 45),
    ('Queso en hebras', 45),
    ('Queso gouda', 45),
    ('Queso mozzarella', 45),
    ('Queso parmesano', 45),
    ('Queso provolone', 45),
    ('Quinoa', 180),
    ('Recao', 7),
    ('Remolacha', 45),
    ('Repollo', 45),
    ('Repollo morado', 45),
    ('Ron de cocina', 180),
    ('Rábano', 7),
    ('Rúcula', 7),
    ('Sal', 180),
    ('Salami', 30),
    ('Salsa barbacoa', 180),
    ('Salsa de salchicha', 180),
    ('Salsa de soya', 180),
    ('Salsa de tomate', 180),
    ('Salsa inglesa', 180),
    ('Sandía', 10),
    ('Sardinas en lata', 180),
    ('Sazonador para tacos', 180),
    ('Sazón con culantro y achiote', 180),
    ('Semillas de calabaza', 180),
    ('Semillas de chía', 180),
    ('Semillas de girasol', 180),
    ('Sobrasada', 30),
    ('Sofrito', 180),
    ('Soya texturizada', 365),
    ('Sémola de maíz', 180),
    ('Tamarindo', 180),
    ('Tayota', 21),
    ('Tomate', 7),
    ('Tomillo', 180),
    ('Toronja', 30),
    ('Tortilla de maíz', 30),
    ('Tortilla de trigo', 30),
    ('Tortilla integral', 30),
    ('Tuna de nopal', 10),
    ('Turrón', 180),
    ('Uchuva', 21),
    ('Uva', 10),
    ('Vainilla', 180),
    ('Vainitas', 7),
    ('Vinagre blanco', 180),
    ('Vinagre de manzana', 180),
    ('Xoconostle', 21),
    ('Yautía', 30),
    ('Yuca', 21),
    ('Zanahoria', 45),
    ('Ñame', 30)
) AS v(name, dias)
WHERE m.name = v.name
  AND m.shelf_life_days = 14;

DO $$
DECLARE quedan integer;
BEGIN
    SELECT count(*) INTO quedan FROM public.master_ingredients WHERE shelf_life_days = 14;
    -- 70 al generarla; el margen admite filas nuevas del catálogo sin volver a fallar.
    IF quedan > 100 THEN
        RAISE EXCEPTION 'P1-PLAN-LOTE-209: siguen % filas con el relleno de 14 días (esperado <= 100)', quedan;
    END IF;
    IF EXISTS (SELECT 1 FROM public.master_ingredients WHERE name = 'Aceite de oliva' AND shelf_life_days = 14) THEN
        RAISE EXCEPTION 'P1-PLAN-LOTE-209: el aceite de oliva sigue en 14 días';
    END IF;
END $$;
